# Generated by Django 4.1.4 on 2022-12-09 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50)),
                ('college', models.CharField(default='college', max_length=50)),
                ('examination', models.CharField(default='examination', max_length=50)),
                ('rollno', models.CharField(default='rollno', max_length=10)),
                ('branch', models.CharField(default='branch', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student_mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odia', models.CharField(default='odia', max_length=3)),
                ('eng', models.CharField(default='english', max_length=3)),
                ('phy', models.CharField(default='physics', max_length=3)),
                ('chem', models.CharField(default='chemistry', max_length=3)),
                ('math', models.CharField(default='math', max_length=3)),
                ('it', models.CharField(default='it', max_length=3)),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student.student_detail')),
            ],
        ),
    ]
