# Generated by Django 4.1.4 on 2022-12-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_mark',
            name='chem',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='student_mark',
            name='eng',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='student_mark',
            name='it',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='student_mark',
            name='math',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='student_mark',
            name='odia',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='student_mark',
            name='phy',
            field=models.CharField(default='', max_length=3),
        ),
    ]
