# Generated by Django 4.1.4 on 2022-12-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_detail_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_detail',
            name='branch',
            field=models.CharField(default='branch', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_detail',
            name='examination',
            field=models.CharField(default='examination', max_length=100),
        ),
    ]
